### ISSUE TITLE
Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by mannipulator** [seratch/notion-translator#12]
Hello again ;)

first of all: Thanks for this blazing fast bugfix today, that seems to work. 

Now I found this error-message:

```
C:\Users\user1\Documents\NotionTranslator>notion-translator --from en --to id --url https://www.notion.so/MyNotionPage

Wait a minute! Now translating the following Notion page:
https://www.notion.so/MyNotionPage

(this may take some time) ...........C:\Users\user1\AppData\Roaming\npm\node_modules\notion-translator\index.js:376
  const newTitle = newPage.properties.title.title[0];
                                            ^

TypeError: Cannot read properties of undefined (reading 'title')
    at createNewPageForTranslation (C:\Users\user1\AppData\Roaming\npm\node_modules\notion-translator\index.js:376:45)
    at C:\Users\user1\AppData\Roaming\npm\node_modules\notion-translator\index.js:421:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.8.0
```

**Comment by RelohDev** [comment]
Hello,
I've got the same error  😉
```shell
root@3c1b4c787426:~# notion-translator   --from en   --to pl   --url https://www.notion.so/reloh/Navigating-the-WebUI-f3137476e4fa4c17a452965bed42fb8f   

Wait a minute! Now translating the following Notion page:
https://www.notion.so/reloh/Navigating-the-WebUI-f3137476e4fa4c17a452965bed42fb8f

(this may take some time) ........./usr/local/lib/node_modules/notion-translator/index.js:376
  const newTitle = newPage.properties.title.title[0];
                                            ^

TypeError: Cannot read properties of undefined (reading 'title')
    at createNewPageForTranslation (/usr/local/lib/node_modules/notion-translator/index.js:376:45)
    at /usr/local/lib/node_modules/notion-translator/index.js:421:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.8.0
```

**Comment by mannipulator** [comment]
Does anyone have a workaround for that bug?

**Comment by Domnin-unchain** [comment]
Hi, I have the same issue. Did you find a solution?

**Comment by nazmy-achmad** [comment]
I'm facing the same issue

**Comment by Mys1ery** [comment]
i got the same issue
![image](https://github.com/user-attachments/assets/185cf22c-21be-4af2-bd63-efa254060b8b)

**Comment by Mys1ery** [comment]
i fix this bug.
![image](https://github.com/user-attachments/assets/46f4c8b4-1573-428e-adf4-600bf2c06ecf)
for me, just replace "newPage.properties.title.title[0]" with "newPage.properties.Name.title[0]", then it will work well
